import { ArchiveFormat, FormatMeta } from '../types';

export const SUPPORTED_FORMATS: FormatMeta[] = [
  // 1. Evrensel
  {
    id: 'zip',
    name: 'ZIP (Deflate / Zip64)',
    ext: '.zip',
    badge: 'Evrensel Standart',
    category: 'Evrensel',
    description: 'Dünya çapında tüm işletim sistemlerinde (Windows, macOS, Linux, iOS, Android) ek yazılım gerektirmeden açılan evrensel standart.',
    algorithm: 'DEFLATE / Enhanced Deflate64',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/zip',
    popularUsage: 'Genel dosya paylaşımı, e-posta ekleri, web indirmeleri, standart arşivleme',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: '7z',
    name: '7-Zip (LZMA / LZMA2)',
    ext: '.7z',
    badge: 'Maksimum Oran',
    category: 'Yüksek Sıkıştırma',
    description: 'Igor Pavlov tarafından geliştirilen açık kaynaklı, çok çekirdekli ve sektör lideri sıkıştırma oranına sahip gelişmiş format.',
    algorithm: 'LZMA2 / BCJ / PPMd / AES-256',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-7z-compressed',
    popularUsage: 'Büyük arşivler, yazılım dağıtımları, yüksek boyutlu yedekleme paketleri',
    defaultLevel: 9,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Maksimum',
  },
  {
    id: 'rar',
    name: 'RAR (Roshal Archive v4/v5)',
    ext: '.rar',
    badge: 'Popüler Standart',
    category: 'Evrensel',
    description: 'Bölünmüş arşiv (multi-volume) ve kurtarma kaydı (recovery record) yetenekleriyle bilinen dayanıklı arşivleme standardı.',
    algorithm: 'RAR5 Proprietary Compression / AES-256',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.rar',
    popularUsage: 'İnternet dosya dağıtımı, çok parçalı ciltler (.part1.rar), medya arşivleri',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },

  // 2. UNIX & DevOps
  {
    id: 'tar',
    name: 'TAR (Tape Archive)',
    ext: '.tar',
    badge: 'Sıfır Ek Yük',
    category: 'UNIX & DevOps',
    description: 'Dosyaları ve klasör izinlerini/hiyerarşilerini sıkıştırma yapmadan tek bir akışta birleştiren UNIX standardı.',
    algorithm: 'POSIX ustar / PAX Container',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-tar',
    popularUsage: 'Docker imaj katmanları, UNIX yedekleme, dosya demetleme',
    defaultLevel: 0,
    compressionSpeed: 'Ultra Hızlı',
    ratioScore: 'Standart',
  },
  {
    id: 'tgz',
    name: 'TAR.GZ / TGZ (Gzip)',
    ext: '.tar.gz',
    badge: 'Linux Standardı',
    category: 'UNIX & DevOps',
    description: 'TAR arşivinin Gzip algoritmasıyla sıkıştırılmış hali. Açık kaynak kod dağıtımlarında en yaygın kullanılan formattır.',
    algorithm: 'TAR + GNU Gzip (RFC 1952)',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/gzip',
    popularUsage: 'GitHub kaynak kodları, Linux paket dağıtımları, sunucu yedekleri',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'gz',
    name: 'GZ (GNU Gzip Stream)',
    ext: '.gz',
    badge: 'Tekil Akış',
    category: 'UNIX & DevOps',
    description: 'Tek bir dosyayı (log, sql dökümü, ham veri) kayıpsız ve hızlı bir şekilde sıkıştırmak için optimize edilmiş akış formatı.',
    algorithm: 'DEFLATE Stream',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/gzip',
    popularUsage: 'Web sunucu logları (.log.gz), PostgreSQL / MySQL dökümleri (.sql.gz)',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'bz2',
    name: 'Bzip2 / TBZ2',
    ext: '.tar.bz2',
    badge: 'Metin Odaklı',
    category: 'Yüksek Sıkıştırma',
    description: 'Burrows-Wheeler dönüşümü ve Huffman kodlaması ile özellikle metin ve kaynak kodlarda Gzip\'e göre daha yüksek oran sunar.',
    algorithm: 'Burrows-Wheeler Transform + Huffman',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-bzip2',
    popularUsage: 'Linux çekirdek sürümleri (kernel.org), akademik veri setleri',
    defaultLevel: 9,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },
  {
    id: 'xz',
    name: 'XZ / TXZ (LZMA2)',
    ext: '.tar.xz',
    badge: 'Modern Linux',
    category: 'Yüksek Sıkıştırma',
    description: 'Modern Linux ve BSD çekirdek dağıtımlarında standart haline gelen, LZMA2 temelli aşırı yüksek sıkıştırma formatı.',
    algorithm: 'LZMA2 Container Stream',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-xz',
    popularUsage: 'Arch Linux / Debian / Fedora paketleri, modern yazılım sürümleri',
    defaultLevel: 9,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Maksimum',
  },
  {
    id: 'zst',
    name: 'Zstandard (ZSTD)',
    ext: '.tar.zst',
    badge: 'Yeni Nesil Hız',
    category: 'Yüksek Sıkıştırma',
    description: 'Meta (Facebook) tarafından geliştirilen, Deflate düzeyinde sıkıştırmayı saniyede yüzlerce megabayt açma hızıyla birleştiren format.',
    algorithm: 'Finite State Entropy (FSE) + Huffman',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/zstd',
    popularUsage: 'Pacman paketleri, veritabanı yedekleri, gerçek zamanlı telemetri akışları',
    defaultLevel: 6,
    compressionSpeed: 'Ultra Hızlı',
    ratioScore: 'Yüksek',
  },
  {
    id: 'lz4',
    name: 'LZ4 (Ultra Hızlı Akış)',
    ext: '.tar.lz4',
    badge: 'Işık Hızı',
    category: 'Yüksek Sıkıştırma',
    description: 'İşlemci önbellek hızlarında (400+ MB/s sıkıştırma, GB/s seviyesinde açma) çalışan ultra düşük gecikmeli algoritma.',
    algorithm: 'Byte-Aligned LZ77 Variant',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-lz4',
    popularUsage: 'Canlı video yayını, RAM disk sıkıştırması, ZFS / Btrfs dosya sistemi katmanları',
    defaultLevel: 1,
    compressionSpeed: 'Ultra Hızlı',
    ratioScore: 'Standart',
  },

  // 3. Medya & Çizgi Roman
  {
    id: 'cbz',
    name: 'CBZ (Comic Book ZIP)',
    ext: '.cbz',
    badge: 'Çizgi Roman & Manga',
    category: 'Medya & Çizgi Roman',
    description: 'Sıralı resim sayfalarını (PNG, JPG, WebP) sayfa sayfa okuyuculara sunan evrensel çizgi roman standardı.',
    algorithm: 'ZIP Image Container',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.comicbook+zip',
    popularUsage: 'Manga okuyucuları, YACReader, CDisplayEx, dijital kütüphaneler',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'cbr',
    name: 'CBR (Comic Book RAR)',
    ext: '.cbr',
    badge: 'Çizgi Roman',
    category: 'Medya & Çizgi Roman',
    description: 'RAR mimarisi üzerine kurulu çizgi roman ve grafik roman arşiv formatı.',
    algorithm: 'RAR Image Container',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.comicbook-rar',
    popularUsage: 'Klasik CBR çizgi roman arşivleri, dijital kütüphane koleksiyonları',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },
  {
    id: 'cbt',
    name: 'CBT (Comic Book TAR)',
    ext: '.cbt',
    badge: 'Hafif Manga',
    category: 'Medya & Çizgi Roman',
    description: 'Sıkıştırmasız TAR tabanlı resim demeti; mobil cihazlarda anında sayfa yüklemesi sağlar.',
    algorithm: 'TAR Image Container',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-cbt',
    popularUsage: 'Düşük güçlü e-mürekkep (E-ink) okuyucular ve hızlı açılan çizgi romanlar',
    defaultLevel: 0,
    compressionSpeed: 'Ultra Hızlı',
    ratioScore: 'Standart',
  },
  {
    id: 'cb7',
    name: 'CB7 (Comic Book 7Z)',
    ext: '.cb7',
    badge: 'Kompakt Manga',
    category: 'Medya & Çizgi Roman',
    description: '7-Zip LZMA algoritmasıyla sıkıştırılmış, en az depolama alanı kaplayan çizgi roman formatı.',
    algorithm: '7Z LZMA2 Image Container',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-cb7',
    popularUsage: 'Büyük manga serileri ve yüksek çözünürlüklü çizgi roman arşivleri',
    defaultLevel: 9,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Maksimum',
  },

  // 4. Disk & Sanallaştırma
  {
    id: 'dmg',
    name: 'DMG (Apple Disk Image)',
    ext: '.dmg',
    badge: 'Apple macOS',
    category: 'Disk & Sanallaştırma',
    description: 'Apple macOS işletim sisteminde sanal sürücü olarak takılabilen (HFS+/APFS) disk imajı formatı.',
    algorithm: 'UDIF / zlib / bzip2 / lzfse',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-apple-diskimage',
    popularUsage: 'macOS yazılım dağıtımı, .app yükleyicileri, disk klonlama',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'iso',
    name: 'ISO 9660 / UDF İmajı',
    ext: '.iso',
    badge: 'Optik & Kurulum',
    category: 'Disk & Sanallaştırma',
    description: 'CD, DVD, Blu-ray ve UEFI işletim sistemi kurulum medyalarının birebir sektör kopyası.',
    algorithm: 'ISO 9660 / Joliet / UDF 2.50',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-iso9660-image',
    popularUsage: 'Windows / Linux kurulum USB ve sanal makine (VMware/VirtualBox/KVM) sürücüleri',
    defaultLevel: 0,
    compressionSpeed: 'Ultra Hızlı',
    ratioScore: 'Standart',
  },
  {
    id: 'wim',
    name: 'WIM (Windows Imaging)',
    ext: '.wim',
    badge: 'Windows Dağıtım',
    category: 'Disk & Sanallaştırma',
    description: 'Microsoft Windows kurulum ve sistem imajları için tasarlanmış tekilleştirmeli (single-instance) dosya tabanlı disk formatı.',
    algorithm: 'LZX / XPRESS Compression',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-ms-wim',
    popularUsage: 'Windows Kurulum (install.wim / boot.wim), Sysprep imajları, kurumsal yedekleme',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },

  // 5. Paket & Dağıtım
  {
    id: 'jar',
    name: 'JAR (Java Archive)',
    ext: '.jar',
    badge: 'Java / JVM',
    category: 'Paket & Dağıtım',
    description: 'Java bytecode (.class), manifest ve kaynak dosyalarını içeren ZIP tabanlı JVM yürütülebilir paket formatı.',
    algorithm: 'ZIP Container + META-INF',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/java-archive',
    popularUsage: 'Java uygulamaları, Spring Boot mikroservisleri, Minecraft modları & eklentileri',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'apk',
    name: 'APK (Android Package)',
    ext: '.apk',
    badge: 'Android Uygulama',
    category: 'Paket & Dağıtım',
    description: 'Android işletim sisteminde çalışan uygulamaların DEX bytecode, manifest ve varlıklarını içeren paket.',
    algorithm: 'ZIP (V2/V3 Signature Compatible)',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.android.package-archive',
    popularUsage: 'Android uygulama geliştirme, sideloading, APK analizi ve açma',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'ipa',
    name: 'IPA (iOS App Package)',
    ext: '.ipa',
    badge: 'Apple iOS',
    category: 'Paket & Dağıtım',
    description: 'Apple iOS / iPadOS cihazlarına yüklenen ve Payload dizini içeren ZIP tabanlı uygulama paketi.',
    algorithm: 'ZIP + Apple Code Signing',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/octet-stream',
    popularUsage: 'iOS uygulama testi (TestFlight), kurumsal dağıtım ve paket inceleme',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
  {
    id: 'deb',
    name: 'DEB (Debian Package)',
    ext: '.deb',
    badge: 'Debian / Ubuntu',
    category: 'Paket & Dağıtım',
    description: 'Debian, Ubuntu ve Mint işletim sistemlerinde kullanılan iki adet TAR arşivi (control ve data) içeren ikili paket.',
    algorithm: 'ar container + TAR.XZ / TAR.GZ',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.debian.binary-package',
    popularUsage: 'APT paket yöneticisi, Linux yazılım kurulum paketleri',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },
  {
    id: 'rpm',
    name: 'RPM (Red Hat Package)',
    ext: '.rpm',
    badge: 'RedHat / Fedora',
    category: 'Paket & Dağıtım',
    description: 'RHEL, Fedora, CentOS ve openSUSE sistemlerinde kullanılan CPIO + XZ tabanlı paket yönetim standardı.',
    algorithm: 'RPM Lead + Header + CPIO.XZ Payload',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/x-rpm',
    popularUsage: 'DNF / YUM paket yöneticisi, kurumsal Linux yazılım dağıtımları',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },
  {
    id: 'cab',
    name: 'CAB (Microsoft Cabinet)',
    ext: '.cab',
    badge: 'Windows Cabinet',
    category: 'Paket & Dağıtım',
    description: 'Microsoft Windows güncelleştirmeleri ve sürücü paketlerinde kullanılan kayıpsız sıkıştırma formatı.',
    algorithm: 'MSZIP / LZX / Quantum',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/vnd.ms-cab-compressed',
    popularUsage: 'Windows Update paketleri, donanım sürücüsü dağıtımları (.inf/.cab)',
    defaultLevel: 6,
    compressionSpeed: 'Dengeli',
    ratioScore: 'Yüksek',
  },
  {
    id: 'appx',
    name: 'APPX / MSIX (Windows App)',
    ext: '.msix',
    badge: 'Windows 11 / Store',
    category: 'Paket & Dağıtım',
    description: 'Modern Windows 10 & 11 Microsoft Store ve kurumsal uygulamaları için yeni nesil sanal alanlı paket.',
    algorithm: 'OPC / ZIP + AppxBlockMap.xml',
    canCompress: true,
    canExtract: true,
    mimeType: 'application/msix',
    popularUsage: 'Microsoft Store uygulamaları, modern Windows masaüstü paketleri',
    defaultLevel: 6,
    compressionSpeed: 'Hızlı',
    ratioScore: 'İyi',
  },
];

export function getFormatMeta(formatId: string): FormatMeta {
  const found = SUPPORTED_FORMATS.find((f) => f.id === formatId);
  if (found) return found;
  return SUPPORTED_FORMATS[0]; // fallback to zip
}

export function detectFormatFromFilename(filename: string): ArchiveFormat {
  const lower = filename.toLowerCase();
  if (lower.endsWith('.tar.gz') || lower.endsWith('.tgz')) return 'tgz';
  if (lower.endsWith('.tar.bz2') || lower.endsWith('.tbz2') || lower.endsWith('.bz2')) return 'bz2';
  if (lower.endsWith('.tar.xz') || lower.endsWith('.txz') || lower.endsWith('.xz')) return 'xz';
  if (lower.endsWith('.tar.zst') || lower.endsWith('.tzst') || lower.endsWith('.zst')) return 'zst';
  if (lower.endsWith('.tar.lz4') || lower.endsWith('.lz4')) return 'lz4';
  if (lower.endsWith('.tar')) return 'tar';
  if (lower.endsWith('.7z')) return '7z';
  if (lower.endsWith('.cbz')) return 'cbz';
  if (lower.endsWith('.cbr')) return 'cbr';
  if (lower.endsWith('.cbt')) return 'cbt';
  if (lower.endsWith('.cb7')) return 'cb7';
  if (lower.endsWith('.dmg')) return 'dmg';
  if (lower.endsWith('.iso')) return 'iso';
  if (lower.endsWith('.rar')) return 'rar';
  if (lower.endsWith('.jar')) return 'jar';
  if (lower.endsWith('.apk')) return 'apk';
  if (lower.endsWith('.ipa')) return 'ipa';
  if (lower.endsWith('.deb')) return 'deb';
  if (lower.endsWith('.rpm')) return 'rpm';
  if (lower.endsWith('.cab')) return 'cab';
  if (lower.endsWith('.msix') || lower.endsWith('.appx')) return 'appx';
  if (lower.endsWith('.wim')) return 'wim';
  if (lower.endsWith('.gz')) return 'gz';
  return 'zip';
}
